# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwise_piS <- function(r_seqs) {
    .Call(`_silentsitesdiv_pairwise_piS`, r_seqs)
}

