// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pairwise_piS
SEXP pairwise_piS(CharacterVector r_seqs);
RcppExport SEXP _silentsitesdiv_pairwise_piS(SEXP r_seqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type r_seqs(r_seqsSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_piS(r_seqs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_silentsitesdiv_pairwise_piS", (DL_FUNC) &_silentsitesdiv_pairwise_piS, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_silentsitesdiv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
